import test from 'node:test';
import assert from 'node:assert/strict';
import * as T from 'three';
import {sectionGeometry,buildMolar,crownGeometry,enamelShell,validateScene,MODEL,ANATOMY} from '../dist/core.mjs';
function signedVolume(g){const a=g.index?g.toNonIndexed():g,p=a.getAttribute('position');let sum=0;for(let i=0;i<p.count;i+=3){const x=new T.Vector3().fromBufferAttribute(p,i),y=new T.Vector3().fromBufferAttribute(p,i+1),z=new T.Vector3().fromBufferAttribute(p,i+2);sum+=x.dot(y.cross(z))/6;}if(a!==g)a.dispose();return sum;}
function area(g){const p=g.getAttribute('position');let sum=0;for(let i=0;i<p.count;i+=3){const a=new T.Vector3().fromBufferAttribute(p,i),b=new T.Vector3().fromBufferAttribute(p,i+1),c=new T.Vector3().fromBufferAttribute(p,i+2);sum+=b.sub(a).cross(c.sub(a)).length()/2;}return sum;}
test('capped cube has the analytical half volume and section area',()=>{const r=sectionGeometry(new T.BoxGeometry(2,2,2),0);assert.equal(r.openChains,0);assert.equal(r.loops,1);assert.ok(Math.abs(area(r.cap)-4)<1e-8);assert.ok(Math.abs(signedVolume(r.surface)+signedVolume(r.cap)-4)<1e-8);});
test('section keeps a socket hole rather than painting it over',()=>{const s=new T.Shape();s.moveTo(-2,-2);s.lineTo(2,-2);s.lineTo(2,2);s.lineTo(-2,2);s.closePath();const h=new T.Path();h.moveTo(-1,-1);h.lineTo(-1,1);h.lineTo(1,1);h.lineTo(1,-1);h.closePath();s.holes.push(h);const g=new T.ExtrudeGeometry(s,{depth:2,bevelEnabled:false});g.translate(0,0,-1);const r=sectionGeometry(g,0);assert.equal(r.openChains,0);assert.equal(r.loops,2);assert.ok(Math.abs(area(r.cap)-12)<1e-7);assert.ok(Math.abs(signedVolume(r.surface)+signedVolume(r.cap)-12)<1e-7);});
test('planes outside the model keep all or none of the geometry',()=>{const g=new T.BoxGeometry(2,2,2);const all=sectionGeometry(g,3),none=sectionGeometry(g,-3);assert.equal(all.loops,0);assert.equal(none.loops,0);assert.ok(Math.abs(signedVolume(all.surface)-8)<1e-8);assert.equal(none.surface.getAttribute('position').count,0);});
test('every authored molar part has finite normals and closed sampled sections',()=>{const parts=buildMolar();for(const part of parts){const p=part.geometry.getAttribute('position'),n=part.geometry.getAttribute('normal');assert.equal(p.count,n.count,part.name);assert.ok(Array.from(p.array).every(Number.isFinite),part.name);assert.ok(Array.from(n.array).every(Number.isFinite),part.name);for(const cut of [-2.3,0,2.1]){const r=sectionGeometry(part.geometry,cut);assert.equal(r.openChains,0,part.name+' at '+cut);r.surface.dispose();r.cap.dispose();}}});
test('inner crown stays inside the outer crown bounding box',()=>{const outer=crownGeometry(),inner=crownGeometry(.84);outer.computeBoundingBox();inner.computeBoundingBox();assert.ok(outer.boundingBox.containsBox(inner.boundingBox));assert.ok(signedVolume(outer)>0);assert.ok(signedVolume(inner)>0);});
test('enamel is a hollow shell with the inner crown excluded',()=>{const r=sectionGeometry(enamelShell(),0),outer=sectionGeometry(crownGeometry(),0),inner=sectionGeometry(crownGeometry(.84),0);assert.equal(r.loops,2);assert.equal(r.openChains,0);assert.ok(Math.abs(area(r.cap)-(area(outer.cap)-area(inner.cap)))<1e-4);});
const state={schema:1,model:MODEL.id,version:MODEL.version,mode:'molar',section:true,cut:0,explode:0,exposure:1,lighting:'studio',labels:true,quality:'balanced',selected:'enamel',hidden:[],camera:[19,7,43],target:[0,-3,0]};
test('scene JSON round-trips without mutating the supplied object',()=>{const value=validateScene(JSON.parse(JSON.stringify(state)));assert.deepEqual(value,state);value.camera[0]=10;assert.equal(state.camera[0],19);});
test('incompatible or malicious scene settings are rejected',()=>{for(const change of [{version:'future'},{hidden:['unknown']},{cut:NaN},{camera:[0,-3,0]},{exposure:99},{quality:'unlimited'},{selected:'unknown'}])assert.throws(()=>validateScene({...state,...change}));});
test('anatomy identifiers are unique and review state is explicit',()=>{assert.equal(new Set(ANATOMY.map(r=>r.id)).size,ANATOMY.length);assert.ok(ANATOMY.every(r=>r.review==='unreviewed'&&r.geometry.length>10));});
