export type TissueId = 'enamel'|'dentin'|'pulp'|'cementum'|'pdl'|'gingiva'|'bone'|'vessels'|'nerve'|'palate'|'tongue';
export interface AnatomyRecord {
  id:TissueId; name:string; color:string; role:string; cells:string; micro:string;
  geometry:string; review:'unreviewed'; sources:string[];
}
const enamelSource='https://doi.org/10.1152/physrev.00030.2016';
const cellSource='https://doi.org/10.1016/j.isci.2021.102405';
export const ANATOMY:AnatomyRecord[]=[
 {id:'enamel',name:'Enamel',color:'#efe5cf',role:'Mineralized outer crown; protects the underlying dentin.',cells:'Mature erupted enamel is acellular. Ameloblasts form enamel during development.',micro:'Hydroxyapatite crystallites organized into enamel rods and interrod enamel.',geometry:'Authored crown surface with five cusp reliefs. Thickness is illustrative.',review:'unreviewed',sources:[enamelSource]},
 {id:'dentin',name:'Dentin',color:'#d5ad67',role:'Mineralized body of the crown and roots, surrounding the pulp space.',cells:'Odontoblast cell bodies line the pulp–dentin boundary; their processes enter dentinal tubules.',micro:'Tubules through a mineralized collagen matrix. Tubule density is not resolved here.',geometry:'Nested crown and divergent root volumes. Junctions require expert review.',review:'unreviewed',sources:[enamelSource,cellSource]},
 {id:'pulp',name:'Pulp & canals',color:'#b7515b',role:'Living connective tissue within the chamber and root canals.',cells:'Fibroblasts, odontoblast boundary, endothelial, immune and neural-associated populations.',micro:'Vascular and neural networks within a soft connective matrix.',geometry:'Chamber, illustrative pulp horns and three canal paths; not a specimen-specific canal system.',review:'unreviewed',sources:[cellSource]},
 {id:'cementum',name:'Cementum',color:'#c9ba94',role:'Mineralized root covering and attachment interface.',cells:'Cementoblasts at the surface; cementocytes occur in cellular cementum.',micro:'Mineralized matrix with extrinsic and intrinsic collagen fibers.',geometry:'Root covering is thickened for visibility; not a calibrated tissue thickness.',review:'unreviewed',sources:[enamelSource]},
 {id:'pdl',name:'Periodontal ligament',color:'#b38d7c',role:'Connective tissue between cementum and alveolar socket.',cells:'Fibroblasts, vascular, immune and progenitor populations.',micro:'Collagen fiber bundles, vessels and nerves. Fiber directions are contextual, not mechanical inputs.',geometry:'Illustrative root envelopes and socket gap; not a stress simulation.',review:'unreviewed',sources:[cellSource]},
 {id:'gingiva',name:'Gingiva',color:'#cf7679',role:'Soft tissue surrounding the cervical tooth region.',cells:'Stratified squamous epithelial cells over connective tissue containing fibroblasts, vessels and immune cells.',micro:'Epithelial/connective tissue interface and collagen-rich supporting tissue.',geometry:'Scalloped collar with neighboring papillae; surface stippling is artistic.',review:'unreviewed',sources:[cellSource]},
 {id:'bone',name:'Alveolar bone',color:'#cfbd98',role:'Tooth-supporting bone surrounding the periodontal socket.',cells:'Osteoblast, osteocyte and osteoclast populations with marrow and vascular context.',micro:'Cortical socket boundary and trabecular interior. Surface pores are a material illustration.',geometry:'Socket-shaped block with root envelopes; no remodeling model.',review:'unreviewed',sources:[enamelSource]},
 {id:'vessels',name:'Vascular supply',color:'#bf4d53',role:'Illustrative arterial and venous routes entering through the apical region.',cells:'Endothelial cells and associated mural/perivascular populations.',micro:'Branching lumen network. Flow and perfusion are not calculated.',geometry:'Schematic paths; vessel diameters and branching are not measured.',review:'unreviewed',sources:[cellSource]},
 {id:'nerve',name:'Neural supply',color:'#dbc179',role:'Schematic sensory route through the apical region into the pulp.',cells:'Neural and supporting glial populations.',micro:'Fiber bundles; no electrophysiology or sensation calculation.',geometry:'Illustrative centerline paths, not inferred from imaging.',review:'unreviewed',sources:[cellSource]},
 {id:'palate',name:'Palate context',color:'#b87377',role:'Roof of the oral cavity with hard/soft palate context.',cells:'Oral epithelium with underlying connective and region-dependent glandular tissues.',micro:'Rugae relief is shown at the surface; tissue layers are not resolved.',geometry:'Authored vault, raphe and posterior transition; not reviewed anatomy.',review:'unreviewed',sources:[]},
 {id:'tongue',name:'Tongue context',color:'#ba666d',role:'Muscular oral structure shown with dorsal surface relief.',cells:'Skeletal muscle, epithelial, vascular, neural and immune populations.',micro:'Surface papillae are an artistic texture; taste structures are not simulated.',geometry:'Authored tapered dome; internal muscle architecture is not modeled.',review:'unreviewed',sources:[]}
];
export const MODEL={id:'adult-mandibular-left-first-molar',version:'0.1.0',fdi:'36',universal:'19',
 units:'illustrative model units',axes:{x:'mesiodistal',y:'occlusoapical',z:'buccolingual'},
 provenance:'Locally authored parametric geometry; no patient data or imported reference mesh.',review:'unreviewed',
 dimensions:'Nominal proportions only. Not calibrated for clinical measurements.',sources:[enamelSource,cellSource]};
