// Published observations and authored choices are separate records. Nothing here
// supplies a parameter to MARSE's microbial solver or changes its saved arrays.
export const REFERENCES = {
 crown:{title:'Lee et al., 2016 · crown morphology',url:'https://pmc.ncbi.nlm.nih.gov/articles/PMC6395370/',population:'71 Taiwanese dental patients; 141 first molars; non-DL subgroup n=73 teeth',method:'Dental casts; maximum diameters parallel to the occlusal plane',limit:'Selected clinical cohort, not a universal adult mean; cast distortion and paired teeth matter.'},
 roots:{title:'Tomaszewska et al., 2018 · micro-CT',url:'https://doi.org/10.1002/ca.23080',population:'Original imaging: 108 first, 120 second and 146 third mandibular molars',method:'Micro-CT and separately reported meta-analysis',limit:'Variation of roots, canals and foramina; no patient-specific reconstruction.'},
 furcation:{title:'Qiu et al., 2024 · root furcation',url:'https://doi.org/10.1186/s12903-024-04892-5',population:'50 extracted first molars, deliberately split into 25 two-rooted and 25 three-rooted teeth',method:'Calibrated micro-CT reconstructions',limit:'The 50/50 sampling is not a prevalence estimate; study dimensions are not individual landmarks.'},
 attachment:{title:'Vacek et al., 1994 · dentogingival histometry',url:'https://pubmed.ncbi.nlm.nih.gov/7928131/',population:'10 adult cadaver jaws; 171 tooth surfaces',method:'Histomorphometry',limit:'Histological dimensions differ from clinical probing; cohort observations do not calibrate this pocket.'},
 nerves:{title:'Lee et al., 2015 · inferior alveolar neurovascular bundle',url:'https://pubmed.ncbi.nlm.nih.gov/26433190/',population:'20 dentulous hemimandibles; 10 donors; mean age 58.2 years',method:'Histological sections and light microscopy',limit:'Supports regional bundle relationships; our rendered course and diameters remain schematic.'},
 pathway:{title:'NCBI anatomy reference · mandibular nerve',url:'https://www.ncbi.nlm.nih.gov/books/NBK507820/',population:'Anatomical reference; not a morphometric cohort',method:'Named peripheral nerve course',limit:'Does not establish the coordinates of this generic head or a measured central projection.'},
 plaque:{title:'Zijnge et al., 2010 · natural-tooth biofilm',url:'https://pmc.ncbi.nlm.nih.gov/articles/PMC2827546/',population:'Seven teeth from four people with advanced periodontitis',method:'Static FISH microscopy on retained tooth-associated biofilms',limit:'Across-biofilm spatial observations, not a growth movie or universal pocket-depth distribution.'},
 supra:{title:'Mark Welch et al., 2016 · supragingival biogeography',url:'https://pmc.ncbi.nlm.nih.gov/articles/PMC4760785/',population:'Human supragingival dental plaque',method:'Multiplexed spectral FISH imaging',limit:'Observed consortia belong to supragingival plaque; proposed assembly dynamics are inferred.'},
 tongue:{title:'Wilbert et al., 2020 · tongue dorsum',url:'https://pmc.ncbi.nlm.nih.gov/articles/PMC7179516/',population:'Human tongue-dorsum samples',method:'Spectral FISH microscopy and spatial proximity analysis',limit:'Fixed snapshots support a proposed growth model, not a measured temporal trajectory.'},
 habitats:{title:'Segata et al., 2012 · oral habitat composition',url:'https://pmc.ncbi.nlm.nih.gov/articles/PMC3446314/',population:'Healthy adult Human Microbiome Project sampling',method:'Sequence-based community composition across oral sites',limit:'Composition is not individual-cell position, contact or migration evidence.'},
 boneDefects:{title:'Clinical CBCT and surgical bone-defect measurements, 2015',url:'https://pubmed.ncbi.nlm.nih.gov/26229268/',population:'Clinical periodontal-defect study; no dimensions imported into this model',method:'CBCT measurements compared with direct surgical measurements',limit:'Documents bone defects, not a progression clock or a calibration for the storyboard.'},
 gingivitis:{title:'Löe et al., 1965 · experimental gingivitis',url:'https://doi.org/10.1902/jop.1965.36.3.177',population:'Human experimental gingivitis cohort',method:'Longitudinal clinical observation',limit:'Plaque/gingivitis evidence does not supply a periodontitis-to-bone-loss clock.'}
} as const;
export type ReferenceKey=keyof typeof REFERENCES;
// Local-frame presentation transform anchored by the existing full crown bounds.
// This does not calibrate roots, tissue widths, pocket depth, arch or head.
export const CROWN_REFERENCE={md:11.13,bl:10.47,sourceBounds:{md:10.199811,bl:8.500974},
 scale:[11.13/10.199811,11.13/10.199811,10.47/8.500974] as [number,number,number],
 claim:'Reference-sized crown; surrounding dimensions are authored, not measured'};
export interface Parameter {name:string;definition:string;reference:string;units:string;chosen:string;classification:'Measured reference'|'Representative choice'|'Artistic approximation'|'Unresolved';source:ReferenceKey;}
export const PARAMETERS:Parameter[]=[
 {name:'FDI 36 crown · mesiodistal',definition:'Maximum crown diameter parallel to the occlusal plane',reference:'11.13 ± 0.40 mm, mean ± SD; non-DL n=73',units:'mm',chosen:'11.13 mm; display reference only',classification:'Measured reference',source:'crown'},
 {name:'FDI 36 crown · buccolingual',definition:'Maximum crown diameter parallel to the occlusal plane',reference:'10.47 ± 0.27 mm, mean ± SD; same subgroup',units:'mm',chosen:'10.47 mm; display reference only',classification:'Measured reference',source:'crown'},
 {name:'Root / canal configuration',definition:'External roots and internal main canal paths counted separately',reference:'Micro-CT documents variation',units:'count',chosen:'Two roots; three authored main canals (two mesial, one distal)',classification:'Representative choice',source:'roots'},
 {name:'Cusp configuration',definition:'Occlusal cusp identities',reference:'Five-cusp crown measured in the selected study',units:'count',chosen:'MB, DB, distal, ML and DL; neighbor 37 four cusps; 35 three-cusp variant',classification:'Representative choice',source:'crown'},
 {name:'Root length / crown height',definition:'CEJ to root apex / cusp tip',reference:'No compatible length distribution extracted for this model',units:'unscaled authored coordinates',chosen:'Existing sculpt; no mm claim',classification:'Unresolved',source:'roots'},
 {name:'Root trunk / furcation',definition:'CEJ to bifurcation; root divergence and concavities',reference:'Reference micro-CT series; two- and three-rooted groups kept separate',units:'mm in source; authored model units here',chosen:'Existing two-root sculpt; numerical calibration pending',classification:'Artistic approximation',source:'furcation'},
 {name:'Histological sulcus',definition:'Histological sulcus depth, not probing depth',reference:'1.34 ± 0.84 mm; 171 surfaces / 10 jaws',units:'mm in source',chosen:'No source mean assigned to either pocket preset',classification:'Measured reference',source:'attachment'},
 {name:'Epithelial attachment',definition:'Histological epithelial attachment length',reference:'1.14 ± 0.49 mm; same sample',units:'mm in source',chosen:'Separate lining and attachment illustration; not calibrated',classification:'Measured reference',source:'attachment'},
 {name:'Connective attachment',definition:'Histological connective tissue attachment length',reference:'0.77 ± 0.32 mm; same sample',units:'mm in source',chosen:'Separate supporting compartment; not calibrated',classification:'Measured reference',source:'attachment'},
 {name:'Healthy landmarks',definition:'Gingival margin / epithelial attachment / bone crest',reference:'Authored baseline, not measured site histology',units:'model units',chosen:'Margin 0.35; attachment −1.65; nominal crest −3.5',classification:'Artistic approximation',source:'attachment'},
 {name:'Periodontitis landmarks',definition:'Margin, attachment and crest independently authored',reference:'No disease-progression calibration',units:'model units',chosen:'Margin −0.15; attachment −6.2; distal crest about −8.50',classification:'Artistic approximation',source:'attachment'},
 {name:'Enamel / cementum / PDL widths',definition:'Tissue envelopes around the crown and root',reference:'No compatible local thickness map imported',units:'model units',chosen:'Authored and exaggerated for visibility',classification:'Unresolved',source:'roots'},
 {name:'Pulp and neurovascular paths',definition:'Chamber, horns, canals, apical entries and mandibular route',reference:'Anatomical identity supported; coordinate course not measured',units:'model units',chosen:'Three canal paths; separate nerve, artery and vein; enlarged diameters',classification:'Artistic approximation',source:'nerves'},
 {name:'Arch placement / tooth inclinations',definition:'Dental midline, occlusal plane and local tangent registration',reference:'No registered whole-head atlas imported',units:'model units / authored pose',chosen:'Coherent procedural arch; selected segment registered by one transform',classification:'Artistic approximation',source:'roots'},
 {name:'Tongue / cheek distances',definition:'Distance between named landmarks in a specified pose',reference:'No compatible pose-specific measurement imported',units:'unresolved',chosen:'No numerical ruler; open-mouth context only',classification:'Unresolved',source:'habitats'},
 {name:'Biofilm cells / matrix / elapsed time',definition:'Microbial arrangement and assembly stages',reference:'Static spatial imaging; temporal transitions inferred or illustrative',units:'no physical scale / no elapsed-time units',chosen:'Anonymous schematic glyphs; stage names; no growth or flux rates',classification:'Artistic approximation',source:'plaque'}
];
export const NERVE_STEPS=[
 {title:'Pulpal branches',text:'Sensory endings branch within living pulp. The pictured filaments are enlarged schematic routes through the three authored canals.'},
 {title:'Apical entry and dental branches',text:'Neural and vascular branches enter through apical foramina. A root and a canal are different structures; accessory anatomy is not resolved.'},
 {title:'Inferior alveolar nerve',text:'Dental branches connect to the inferior alveolar nerve within the mandibular canal. Its mental branch supplies the lower lip and chin; it is not the molar pulpal branch.'},
 {title:'Mandibular division · V3',text:'The inferior alveolar nerve joins the mandibular division in the infratemporal region. V3 passes through the foramen ovale. Buccal and lingual gingival sensory routes have separate distributions.'},
 {title:'Trigeminal ganglion',text:'Primary sensory neuron cell bodies lie in the trigeminal ganglion. This is a sensory ganglion; it is not a motor relay.'},
 {title:'Sensory root → brainstem',text:'Central sensory axons enter the brainstem via the trigeminal sensory root. This diagram stops at brainstem entry; it does not map individual axons, brainstem nuclei or cortical pain processing.'}
] as const;
